### PR TITLE
Move symfony extra bundle into the suggest section

### PR DESCRIPTION
**Pull request by mvrhov**
Not everybody wants to use extra bundle. IMO it should be inside of suggest section and if one wants to use it then it should require it as explicit dependency.

### CODE REVIEW

**Comment by nicoschoenmaker** [comment]
Interesting point of view. I guess the bundle mostly works fine without the extra bundle.

If we want to support this, we should include in our Travis build a version with, and a version without the extra bundle.

So that we verify
- the bundle + the additional feature works when the `sensio/framework-extra-bundle` is included
- the bundle works without the `sensio/framework-extra-bundle`. (With a skipped test for when the bundle isn't included)

Otherwise I'm afraid we'd end up breaking the 2nd case from time to time. Which wouldn't be good for you :wink:

That kind of things can be done in the `travis.yml`, see [example](https://github.com/liip/LiipHyphenatorBundle/blob/master/.travis.yml).

**Comment by yannickl88** [comment]
While I understand the points, I would like to mention that the `ParameterConverter` option will be removed with `2.0,0` because you now need to use the [`HandlerFactory`](https://github.com/hostnet/form-handler-component/blob/master/src/FormHandler/HandlerFactory.php) for creating handlers.

So for me, I would rather leave it be and just wait for `2.0.0`.

**Comment by iltar** [comment]
I don't think it's fair to require the Sensio framework extra bundle if they use the latest version, this should indeed be optional. The annotation library was giving compatibility issues on the latest version due to php56 still being support (will be dropped with 2.0). I've pushed a fix for the formatting and dependency issue to your branch.

The latest versions are failing and should be solved by fixing #40, which is not something you have to worry about.

@mvrhov, there is still one failure left, can you fix that? https://travis-ci.org/hostnet/form-handler-bundle/jobs/286431186

**Comment by mvrhov** [comment]
I think this should be ready now.

**Comment by yannickl88** [comment]
I've created the 1.4.0 tag which includes your changes.

**Comment by mvrhov** [comment]
Yay, got rid of unneeded dependency :)

**Pull request merged**
