### PR TITLE
Readme is a lot smaller, refers to wiki instead

### PR DESCRIPTION
**Pull request by iltar**
Instead of having the whole documentation in the readme, we want to use the wiki instead. This reduces the chaos and clutter in this repository and makes it easier to find what you need.

Preview: https://github.com/iltar/form-handler-bundle/blob/readme/cleanup/README.md

### CODE REVIEW

**Comment by Ricknox** [comment]
👍 
Looks fine to me.

**Comment by javiereguiluz** [comment]
It looks very nice! Simple and easy to understand. Good work!!

**Comment by iltar** [comment]
WouterJ made a good comment saying that readme files are not just for the github gui when talking about the license. I will add a mention of the license on monday before merging this.

@yannickl88 Do you think we're ready to release a stable after this merge?

**Comment by yannickl88** [comment]
@iltar Yeah, adding a header with licence information might be useful then. I noticed the LICENCE file does not contain the licence name (or at least not at first glance). Only the Github UI shows it, so I agree with WouterJ.

So if that is resolved, it's fine with me to merge this.

**Comment by yannickl88** [comment]
Added license header. Is it okay for you @iltar?

**Comment by iltar** [comment]
@yannickl88 Looks good to me!

**Comment by yannickl88** [comment]
shall we merge then?

**Comment by yannickl88** [comment]
I think we are also ready for a 1.2.0 release then right?

**Pull request merged**
