### PR TITLE
Add service aliases

### LINKED ISSUE #48: Add service aliases for autowiring
Currently we have to manually alias our services to the FQCN and interfaces to make autowiring possible.

### PR DESCRIPTION
**Pull request by GawainLynch**
This enables the services to be DIed on type hint:

`public function myAction(Request $request, HandlerFactory $handlerFactory): Response`

Fixes #48

### CODE REVIEW

**Comment by iltar** [comment]
What if we do it the other way around, alias the old definitions and make the FQCN leading? I would also like to see an alias for the interface, pointing towards the implementation, this makes it possible to easily decorate (think logging/timeline for example).

Additionally, can you add a test to verify if the autowiring behavior works in properly in 3.3+? This is merely to verify that the service config is written in a way it won't fail after updating.

**Comment by GawainLynch** [comment]
Happy to switch them around, I was unsure of the preferred approach wrt BC.

All my work in on 4.0.x, so yep, they're working there, but happy to run up a 3.4 site to check as well if you think it relevant.

**Comment by iltar** [comment]
Regarding tests I mean this one: https://github.com/hostnet/form-handler-bundle/blob/master/test/Functional/Fixtures/config/config_33.yml

Can you add a public class here that requires in the constructor (or optionally arguments for controller if you like):
 - `FormProviderInterface`
 - `SimpleFormProvider`
 - `HandlerFactoryInterface`
 - `HandlerFactory`

This way we can keep the guarantee that this works.

**Comment by GawainLynch** [comment]
Should be GTG now! Thanks for your patience.

**Comment by iltar** [comment]
Can you also add aliases to the interfaces? Other than that, looks good to me!

**Comment by GawainLynch** [comment]
Gedaan!

**Comment by hboomsma** [comment]
I'll ask Iltar to draft a release after we discussed #46

**Comment by GawainLynch** [comment]
Much appreciated. Thanks for a great bundle :+1:

**Pull request merged**
